import React, { useState } from 'react';
import { Check, LockKeyhole, X } from 'lucide-react';
import { emitFeedback } from '../../../components/FeedbackModal';

export const inputClass = 'mt-2 w-full rounded-xl border border-zinc-200 bg-zinc-50 px-3.5 py-3 text-sm text-zinc-900 outline-none transition-colors placeholder:text-zinc-400 focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/15 dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-100';
export const buttonClass = 'transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-zinc-950';

export function Login({ onLogin }) { const [password, setPassword] = useState(''); const submit = (event) => { event.preventDefault(); fetch('/api/auth/login', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data?.error || 'Não foi possível entrar.'); sessionStorage.setItem('idz_admin_csrf', data.csrf); onLogin(); }).catch((err) => emitFeedback('error', err?.message || 'Não foi possível entrar.')); }; return <main className="mx-auto flex min-h-[70vh] max-w-md items-center px-4 py-16"><div className="w-full rounded-3xl border border-zinc-200 bg-white p-8 shadow-xl shadow-zinc-200/40 dark:border-zinc-800 dark:bg-zinc-900 dark:shadow-black/20"><div className="mb-7 flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-500/10 text-emerald-500"><LockKeyhole className="h-6 w-6" /></div><p className="mb-2 font-mono text-[11px] font-bold uppercase tracking-[0.2em] text-emerald-600 dark:text-emerald-400">Área restrita</p><h1 className="text-3xl font-bold tracking-tight">Painel editorial</h1><p className="mt-2 text-sm leading-relaxed text-zinc-500">Escreva, publique e cuide da conversa do Blog do Zero.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-xs font-semibold text-zinc-600 dark:text-zinc-400">Senha<input required name="password" autoComplete="current-password" autoFocus type="password" value={password} onChange={(event) => setPassword(event.target.value)} className={inputClass} /></label><button className={`${buttonClass} w-full rounded-xl bg-emerald-500 py-3 text-sm font-bold text-zinc-950 hover:bg-emerald-400`}>Entrar no painel</button></form></div></main>; }
export function Panel({ children, className = '' }) { return <section className={`rounded-3xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900 ${className}`}>{children}</section>; }
export function PanelTitle({ icon: Icon, eyebrow, title, action }) { return <div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><div className="mt-0.5 rounded-xl bg-emerald-500/10 p-2 text-emerald-600 dark:text-emerald-400"><Icon className="h-4 w-4" /></div><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-zinc-400">{eyebrow}</p><h2 className="mt-1 text-lg font-bold tracking-tight">{title}</h2></div></div>{action}</div>; }
export function CommentCard({ comment, onModerate }) { const approved = comment.status === 'approved'; return <article className="rounded-2xl border border-zinc-200 bg-zinc-50/70 p-4 dark:border-zinc-800 dark:bg-zinc-950/60"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold text-emerald-600 dark:text-emerald-400">{comment.author}</p><p className="mt-1 break-words text-sm leading-relaxed text-zinc-700 dark:text-zinc-300">{comment.text}</p><p className="mt-2 truncate text-[11px] text-zinc-400">Em: {comment.postTitle}</p></div><span className={`shrink-0 rounded-full px-2 py-1 font-mono text-[9px] font-bold uppercase tracking-wide ${approved ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400' : 'bg-amber-500/10 text-amber-600 dark:text-amber-400'}`}>{approved ? 'publicado' : comment.status === 'pending' ? 'aguardando' : 'rejeitado'}</span></div><div className="mt-3 flex gap-2 border-t border-zinc-200 pt-3 dark:border-zinc-800">{!approved && <button type="button" onClick={() => onModerate(comment, 'approved')} className={`${buttonClass} inline-flex items-center gap-1.5 rounded-lg bg-emerald-500 px-2.5 py-1.5 text-[11px] font-bold text-zinc-950 hover:bg-emerald-400`}><Check className="h-3.5 w-3.5" />Aprovar</button>}{comment.status !== 'rejected' && <button type="button" onClick={() => onModerate(comment, 'rejected')} className={`${buttonClass} inline-flex items-center gap-1.5 rounded-lg border border-zinc-200 px-2.5 py-1.5 text-[11px] font-bold text-zinc-500 hover:border-red-300 hover:text-red-500 dark:border-zinc-800`}><X className="h-3.5 w-3.5" />Rejeitar</button>}</div></article>; }
